source 'https://rubygems.org'

gem 'compass', '~> 1.0.0'
gem 'middleman'
gem 'middleman-livereload', '~> 3.1.0'
gem 'middleman-blog'
gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]
gem 'compass-placeholders'
gem 'livingstyleguide', path: '..'

platforms :mri_18 do
  gem 'ruby18_source_location'
end

